### ISSUE TITLE
Evaluate the use of redfish

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#100]
As a SCS Operator automated firmware updates would ease my life enormously.
We want to evaluate the use of redfish.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] https://github.com/osism/issues/issues/245
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
@berendt @garloff is this something that should be tackled in the r7 development cycle?

**Comment by garloff** [comment]
Definitely an important topic, yes
