### ISSUE TITLE
Evaluate current state of CloudMon

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#106]
A lot has happenend since we last looked at CloudMon. In order to be aware of what is happening around us we should take a look at the current state of CloudMon.

https://stackmon.org/

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] There is an understanding on if and how cloudman can be of use for us
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by piobig2871** [comment]
after careful  consideration, we estimated adaptation of the CloudMon will be to complex and that the primary goal for VP12 is to port it to Gherkin/Python approach
