### ISSUE TITLE
Turn requirements from StatusPage discussion into epic

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#107]
Together with various CSPs we've collected requirements for a StatusPage applications. See this GH discussion: 
https://github.com/orgs/SovereignCloudStack/discussions/89

Let's turn this into an epic with associated user stories.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] epic is laid out
- [x] All acceptance criteria are met

**Comment by fkr** [comment]
See #123
