### ISSUE TITLE
Cloud-in-a-Box

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#116]
As the SCS project / a project team member, I want to have a "small" device that I can carry around to present SCS at conferences or fairs. The box should be able to demonstrate some basic functionality, e.g. creating k8s clusters, deploying VMs, cloud monitoring, alerting, migrating workloads from cloud to edge, etc. 

As a PO / as a community member, I want to have an environment where I can try out the things we build. While the testbed is nice, the testbed in a cloud environment feels very distant. A local environment like a cloud-in-a-box would allow me to testdrive the deployment and also run workloads as well as run testsuites.

As a company that wants to try out SCS (= OpenStack) which previously had another solution cloud-in-a-box allows me to get a first impression before buying into this technology.

Brainstorming: https://input.osb-alliance.de/p/cloud-in-a-box

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #129 
- [x] #143 
- [x] Hardware ordering for SCS Projectteam
- [x] Evaluate current status of manager-installer/node-image
- [x] https://github.com/osism/cloud-in-a-box/issues/16
- [x] https://github.com/osism/cloud-in-a-box/issues/17
- [x] https://github.com/osism/cloud-in-a-box/issues/55
- [x] https://github.com/osism/cloud-in-a-box/issues/59
- [x] #130
- [x] https://github.com/SovereignCloudStack/issues/issues/216
- [x] https://github.com/osism/cloud-in-a-box/issues/62
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by garloff** [comment]
Image for CiaB works.
Making it more generic (detecting disks ...) is work-in-progress.

**Comment by garloff** [comment]
Also WIP:
* Creating users, projects, flavors, ... in installed
* Network connectivity
* Documentation (Quick-Start. Goal: point to relevant pieces in testbed docu)

**Comment by fkr** [comment]
We should refine this epic in order to have a clear boundary between R4 and R5 work.

**Comment by berendt** [comment]
For R4: the name server issue will be fixed. Everything else is done and in a good state.

For R5: Ceph deployment.

2nd NIC is a nive to have.
