### ISSUE TITLE
Use of DVR

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#119]
As the SCS community we should dive into the topic of DVR - since we just faced the first deployment with DVR.

WIP - this needs further refinement

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #118 
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by berendt** [comment]
Discuss: Wavestack dropped DVR. We should document that it is not recommended to use DVR at all.

**Comment by matfechner** [comment]
add to documentation: https://github.com/osism/documentation/pull/422

**Comment by berendt** [comment]
Added note to the release notes as well: https://github.com/osism/release/pull/506

**Comment by fkr** [comment]
A remark about the 'not supported nature of DVR' as been added to the R3 notes. As such, this can be closed.
