### ISSUE TITLE
MVP0: Status Page Application for SCS Operators

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#123]
As a SCS Operator I want to live the Open Operations way of life. This requires a Status Page in order to be transparent about issues in my environment.

Requirements for a status page like that were collected with the SCS community: https://github.com/orgs/SovereignCloudStack/discussions/89

This epic should collect all user stories around this topic.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #121 
- [x] #122 
- [x] #169
- [x] #170 
- [x] #171
- [x] #172
- [x] #173
- [x] #179 
- [x] #174
- [x] #175
- [x] #176
- [x] #177
- [x] #180 
- [x] https://github.com/SovereignCloudStack/issues/issues/223
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
