### ISSUE TITLE
Document the gory details of OSISM

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#124]
As a SCS operator a good and thorough understanding of OSISM is needed in order to make the best use of it.
We need to make sure OSISM is documented in such a way.
This epic is an outcome of our hands on session on OSISM and multi-inventory setups.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] https://github.com/osism/issues/issues/263
- [x] https://github.com/osism/issues/issues/265
- [ ] https://github.com/osism/issues/issues/266
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
https://osism.github.io

**Comment by fkr** [comment]
Idea is that with the updated documentation that exists now @scoopex will build up the scs lab environment.
Based on that outcome we will see wether the documentation now suffices.

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/docs/issues/101
