### ISSUE TITLE
OSISM needs to support custom.* environments

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#125]
As a SCS Operator it is needed to have support for custom.* environments in OSISM.
This is an outcome of our hands-on session on multi-inventory handling in OSISM.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] https://github.com/osism/issues/issues/262 
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated
