### ISSUE TITLE
SOSreport-like functionaly for SCS installations

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#135]
As a SCS Operator, I'd like to have SOSreport-like functionality at hand in order to compile informations about my environment easily.

As a SCS Developer / SCS Integrator it is much more convenient to tell a SCS Operator to run SOSreport instead of explaining how to manually compile informations about the environment.

While this will start on the iaas layer, this topic touches all layers of SCS in the end.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] https://github.com/osism/issues/issues/47
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
