### ISSUE TITLE
Preparation of OpenStack Yoga

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#146]
As a potential SCS operator, I want to have the ability to deploy (a well-working and tested) OpenStack Yoga with SCS R3 (2022-09) release.
As existing SCS operator, I want to have the ability to seamlessly upgrade from previous SCS R2 (Xena) to SCS R3 (Yoga).

## TODO
- [x] Prepare images and playbooks
- [x] Test deployment
- [ ] Prepare release notes (changes vs. Xena etc.)
- [x] Test upgrade
- [x] Document upgrade
- [x] Add daily deployment testing of Yoga in CI

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by garloff** [comment]
New role access model / scoping in Yoga is not yet activated by default, needs more testing and maturing.
https://github.com/osism/issues/issues/269
Focus topic for R4.

**Comment by garloff** [comment]
Daily CI on yoga, use stable branches ("zuul-3") in testbed.
Upgrade test is incomplete, not yet automated, documentation for test missing.
Manual tests have been carried out successfully.

Enabling automated upgrade tests for yoga is a goal for R3, own story.

**Comment by garloff** [comment]
Release Notes: Link upstream docs, only reproduce highlights relevant for SCS in our own docs.

**Comment by garloff** [comment]
Services to test: OpenStack core, octavia, designate, barbican, ceilometer (see testbed deployment scope).
http://docs.osism.de/testbed/overview.html#software-bill-of-materials-sbom

**Comment by fkr** [comment]
Test upgrades still cause problems according to @ra-beer.
Will be verified by tomorrow. If need be, a separate call will be scheduled.

**Comment by berendt** [comment]
Testbed switched to Yoga by default: https://github.com/osism/testbed/commit/21ef67458f46205dee34f339425be6952f72243d

**Comment by berendt** [comment]
Upgrade tests in testbed enabled (Xena -> Yoga), no more problems there.

**Comment by berendt** [comment]
An open point at the moment is to scan the release notes of Yoga for special features and to list them in the release notes of OSISM. Everything else is done.
