### ISSUE TITLE
Use of Ansible v6 for all OSISM playbooks and collections

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#147]
As SCS developer, I want to ensure that all playbooks, collections, ... work with ansible v6.
Make ansible v6 the default.

## TODO:
- [x] Test playbooks, collections ... with v6
- [x] Adjust where needed
- [x] Enable v6 as new default
- [x] Mention in release notes

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
