### ISSUE TITLE
Activation of Ubuntu 22.04 tests for all OSISM Ansible collections

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/issues#148]
As a SCS developer I want to do some testing for Ubuntu 22.04 in R3, so we can deliver it as technical preview, so we can move to it for R4 with confidence. It should be good enough for R3 green-field deployment.
Default kolla-ansible is currently still on 20.04.

## TODO
- [x] Ensure CI runs also with 22.04 images: ansible collections

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by berendt** [comment]
Ubuntu 22.04 is part of https://github.com/SovereignCloudStack/issues/issues/158 and not of this user story.

**Comment by garloff** [comment]
ansible-collections all work with 22.04 (with a few adaptations).
