### ISSUE TITLE
Contribute to ORT

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/issues#153]
As an open-source project, we want to collaborate upstream rather than forking so that we can contribute to the original project and join forces.

We have forked the existing GitHub Action repository from @edulix and adapted it to our needs. As discussed during the last Product Board meeting, we want to suggest bringing this upstream and dedicate some of our time in the @oss-review-toolkit community. We should continue working here: https://github.com/oss-review-toolkit/ort/issues/3512

Additionally, we have created a [GitHub Action that builds a ORT Docker image and pushes the artifact to the GitHub Container Registry](https://github.com/SovereignCloudStack/ort-docker). This corresponds to the upstream PR by @andreasdotorg: https://github.com/oss-review-toolkit/ort/pull/5015. We should try to revive this PR and advocate on merging this feature as well as bringing this to the GitHub Action marketplace. Be aware of the running discussion at https://github.com/oss-review-toolkit/ort/issues/2441.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by itrich** [comment]
Discussed with @sschuberth: We will join the next developer meeting after summer break to discuss further contributing options.
