### ISSUE TITLE
Deploy SCS Zuul

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#157]
As a SCS Developer, I want use a CI and testing tool for my Repositories. We want to use Zuul for this.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #198 
- [x] #199 
- [x] #242
- [x] https://github.com/SovereignCloudStack/issues/issues/279
- [x] #243
- [ ] #244
- [x] #292 
- [ ] #323
- [ ] #290
- [x] #351
- [ ] https://github.com/SovereignCloudStack/issues/issues/354
- [x] #400 
- [ ] https://github.com/SovereignCloudStack/issues/pull/436
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by master-caster** [comment]
Since SCS would like to provide a Zuul service for our own workload we need to check the requirements we have.
Thanks to our OSISM colleges we have some progress here.

So the answer is  "it depends" :grin: 
For Zuul and its Nodepool-Services OSISM is using a virtual machine thats resources are limited to:

- 4 vCPUs
- 8 GB RAM

That fits to the projects recommendation for a small Zuul installation. 
Recommendation for storage depends on the amount of images and the amount of job-logs that
are anticipated. The project itself claims 80GB sufficient for a small installation.

Additional resources are required by nodepool. The amount of resources also depends on the
precise workload and how many parallel tasks may exist. 

OSISM uses a flavor of 2 vCPUs and 4 GB RAM which is more than sufficient for smaller tasks like
Linter, Unit-Tests or Doc-Builds and a Node-Count of 3 - 4 nodes.

If we want to test Testbed-Deployments the current implementation needs a static node that uses
the former flavor. But each worker will need access to its own OpenStack-Tenant.

OSISM expects 4 Tenants to be sufficient for SCS right now. 
If we deploy testbed to an OpenStack cloud environment
the quotas each tenant needs are:

- 1 keypair
- 6 security groups (50 security group rules)
- 6 networks with 6 subnetworks
- 1 router
- 30 ports
- 1 floating IP address
- 9 volumes (min 90 GB) plus 140GB root disks (depends on flavors)
- 4 instances (with 28 VCPUs and 104 GByte memory in total)

see also: https://docs.osism.tech/testbed/requirements.html#for-an-environment-on-a-cloud

Thanks a lot to @osfrickler who brought all the details.

**Comment by master-caster** [comment]
A short update on this.
We do have access to wavestack where we will develop test and most likely deploy our zuul environment.
Right now I try to create an ansible playbook that capable to deploy the whole zuul system with all
its parts.

As a basis I'm using the Zuul role provided by OSISM. After osfrickler gave me some good Information
about the role and updated documentation I think we are on a good way.

The role depends on two FQDNs which is discussed here: https://github.com/SovereignCloudStack/issues/issues/242

**Comment by berendt** [comment]
@master-caster Can you please add the playbook to osism/ansible-playbooks as infrastructure/zuul.yml? You can replace the existing playbook.

**Comment by o-otte** [comment]
Added #323 to Epic

**Comment by master-caster** [comment]
- The github app was updated in the SCS Organization
- zuul-config repository moved to scs

**Comment by master-caster** [comment]
githubapp was missconfigured so any event from github couldn't get to zuul

this is now fixed and the first tests from other repositories within the organization were done

**Comment by fkr** [comment]
@jschoone raised the concern, that zuul.scs.community is needed to finish the e2e tests from the containerteam.
As such the idea is that we unblock this by fixing the zuul instance (which is currently not working). Idea is to have a joint session on friday, Sept. 8th.

**Comment by okautz** [comment]
Done with the new Zuul Instance at https://zuul.sovereignit.cloud
