### ISSUE TITLE
Monitoring of OVN Controlplane

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#16]
As a SCS Operator, I want to make sure that the OVN Controlplane is monitored, so that I'm alerted if the controlplane malfunctions.
In order for that to happen, upstream needs to include the required prometheus exporter. 
Once the exporter is included upstream, the necessary alertmanager rules as well as Grafana dashboards need to be roled out by kolla-ansible, as such we need to make sure these are included upstream as well.

## Open Items
- [ ] Write out User-Stories for Exporter, Alertmanager as well as Grafana  + support tasks such as researching wether Zed or Yoga backport
- [ ] Is OpenStack Zed the proper release to be targeted or is a backport feasible upstream?

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Prometheus exporter is included upstream
- [ ] Alertmanager rules have been merged upstream in kolla-ansible
- [ ] Grafana Dashboards for OVN have been merged upstream in kolla-ansible
- [ ] Targeted release is clear
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
