### ISSUE TITLE
OpenStack Image Manager for CSPs

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#168]
As a SCS Operator, I rely on the OpenStack Image Manager to be able to comply with the standard.
The OpenStack Image Manager will manage the images on a SCS compliant cloud.

The OpenStack Image Manager should not only manage the images, but also be able to crawl the images as well as check a SCS cloud carries all necessary images.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] Metadata of the images is managed by OpenStack Image Manager - https://github.com/osism/openstack-image-manager/issues/333
- [x] Integrate image-md-check.py - https://github.com/osism/openstack-image-manager/issues/349
- [x] Add SCS Metadata - https://github.com/osism/openstack-image-manager/issues/332
- [x] Add a validate command - https://github.com/osism/openstack-image-manager/issues/360
~- [ ] Checksums of images are stored and checked - https://github.com/osism/openstack-image-manager/issues/340~
- [x] Check wether Workflow is clear - #197 
- [x] Documentation of the image manager is easily understandable by a SCS Operator - https://github.com/osism/openstack-image-manager/issues/336
- [ ] ~~Image Crawling is included in the image manager - https://github.com/osism/openstack-image-manager/issues/345~~
- [x] CI pipeline - https://github.com/osism/openstack-image-manager/issues/390
- [x] Lightning Talk will be done - @fkr / @berendt

**Comment by fkr** [comment]
https://github.com/osism/openstack-image-manager/issues/345 - will be done in the current sprint by @costelter

**Comment by fkr** [comment]
https://github.com/osism/openstack-image-manager/issues/340 removed from DoD - since too much dependent from upstream

**Comment by fkr** [comment]
https://github.com/osism/openstack-image-manager/issues/333 and https://github.com/osism/openstack-image-manager/issues/332 will be addressed in this sprint.

**Comment by berendt** [comment]
I think it makses sense to also add  https://github.com/osism/openstack-image-manager/issues/349 to the DoD.

**Comment by fkr** [comment]
@berendt good one. added it. thanks!

**Comment by fkr** [comment]
@ra-beer will comment a more detailed update to the items of the last sprint here.

**Comment by fkr** [comment]
Since some rudimentary update function is present (https://github.com/osism/openstack-image-manager/blob/main/.github/workflows/update-images.yml), we should see wether the incorporation of the image crawling (as proposed in https://github.com/osism/openstack-image-manager/issues/345 will be added in one of the following sprints.

**Comment by fkr** [comment]
To further lay out how the image crawler / image crawling should be incorporated @berendt , @costelter and @fkr should have an exchange. @fkr to schedule.

**Comment by maxwolfs** [comment]
> PR [osism/openstack-image-manager#458](https://github.com/osism/openstack-image-manager/pull/458) open for merging.

PR is merged and online: https://docs.scs.community/docs/category/openstack-image-manager

**Comment by fkr** [comment]
Input from  team IaaS call:

much rather than add arbitrary download capabilities, address upstream to have latest pointers to images.

**Comment by fkr** [comment]
https://github.com/osism/openstack-image-manager/pull/567

**Comment by fkr** [comment]
https://github.com/osism/openstack-image-manager/pull/567 to remove crawler code as discussed in Team IaaS call on May 17th.

**Comment by fkr** [comment]
Crawler now lives here: https://github.com/pluscloudopen/openstack-image-crawler
