### ISSUE TITLE
Logshipping for SCS with the purpose of debugging

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#17]
As a SCS Operator I want to be able to have logs being shipped from the SCS stack into my existing log analysis.

## Definition of Ready:

- [ ] Alternatives to fluentd (which comes with kolla-ansible by default) have been evaluated.
- [ ] Depending on wether we go with fluentd or something different it needs to be sure that upstream work is done properly. Until upstream trickles back to SCS, fluentd will serve as a way to do the logshipping.
- [ ] As a SCS operator I expect documentation and best practice example on how to configure the overlays to point fluentd to an external aggegrator
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by bitkeks** [comment]
What's the status here?
