### ISSUE TITLE
IAM for PaaS Services

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#183]
As a SCS customer I want to access PaaS cloud services like Harbor, DBaaS etc. with my own identity (+consistent login UX without passwords for each service)

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Services need to have a service representation within the identity broker
- [ ] Communication between Services and Identity Broker is secured
- [ ] Service needs to have access to the signing certificate from the Identity broker
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
