### ISSUE TITLE
Role and policy handling within SCS

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#185]
Currently role and policy handling is hard to understand and to get right. Lowering the complexity of getting things right will mitigate security risks.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] https://governance.openstack.org/tc/goals/selected/consistent-and-secure-rbac.html#z-release-timeline_ is understood and taken into consideration for further work on this epic
- [ ] As Customer, I have the ability to have the same roles defined on multiple SCS clouds. (Could be standardized or solved via central management.) [Long-term]
- [ ] As a SCS Customer I'm able to extend the role mappings to my needs, across technical boundaries of individual SCS components. (i.e. Keystone, Identity Broker) [cross-component configuration / policies]
- [ ] As a SCS Customer I'm able to assure that the roles and their mapping is consistent across SCS components within one SCS environment (cloud). This may require periodic reconciliation and reporting inconsistencies to the customer. [higher-level authorization management] [long-term]
- [ ] As SCS developer, I want to avoid dealing with complex and hard to get right keystone policies to define conceptually easy roles, so I avoid screwing up (and potentially creating security issues if I do)
- [ ] Role and policy handling is documented in an easy to understand manor
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
