### ISSUE TITLE
External role mapping to keystone

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#186]
In combination with an external IdP roles can be easily mapped to keystone and the overall role concept is documented and understood.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Standard roles in keystone are evaluated and extended and/or adopted where it makes sense
- [ ] Roles in keystone are documented
- [ ] As SCS Customer, I have the ability to do the management of users in an external IDM system (Identity Provider), that I have anyway and create a mapping of attributes/claims there to the roles.
- [ ] As a SCS Customer, I'm to be able to define that users that match a certain criteria in my IdP are mapped to a certain set of access rights
- [ ] As SCS Customer, I can enable my own IDM system for my own domain can be done via Self-Service, so I don't need to wait for someone approving this
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fzakfeld** [comment]
I would like to map project membership to IDP claims as well, but this is currently limited (see https://review.opendev.org/c/openstack/keystone/+/727891?tab=comments)
