### ISSUE TITLE
SCS can be Identity Provider, not just Service Provider

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#187]
SCS can be the Identity Provider and not just consume other IdPs. This way it is possible to daisy-chain SCS clouds.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] As SCS Customer, I'm able to use the identities that I created and manage in one SCS cloud to control access to projects (in a domain that I own) on another SCS cloud, possibly with some mapping, so I don't need to do IDM multiple times when using multiple SCS clouds.
- [ ] SCS Clouds can be daisy-chained
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
