### ISSUE TITLE
Tenant separation within SCS

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#188]
As a SCS Customer I want to have confidentiality and integrity of the resources I have configured in my domain.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Architecture is properly documented and can easily be reviewed by external parties
- [ ] It is automatically tested that separation of users, projects and domains is secure even in a federated scenario
- [ ] As a SCS Operator I'm able to restrict the customer/tenant admin from Elevation of Privilege (leaving the scope of their domain) by creating new admin account outside of his scope
- [ ] Tenant separation is default, so that tenants are not aware of each other
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
