### ISSUE TITLE
SSI enablement within SCS

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#190]
As the SCS project I want to connect to the GAIA-X world of IDM.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] As a DevOps-Team (SCS Customer) I'm able to use my SSI in order to spawn kubernetes clusters on a set of SCS clouds.
- [ ] SCS is able to connect to the Gaia-X IDM world (i.e. SSI/DID style IDM)
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
