### ISSUE TITLE
CLI/API and Weblogin via federated Identity

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#191]
CLI/API as well as Weblogin (Horizon) are possible with a federated Identity.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] [Setup Keycloak federation in deployed testbed](https://github.com/SovereignCloudStack/issues/issues/210)
- [x] [Research OICD identity federation with v3oidcpassword](https://github.com/SovereignCloudStack/issues/issues/209)
- [x] https://github.com/SovereignCloudStack/issues/issues/221
- [x] https://github.com/SovereignCloudStack/issues/issues/232
- [x] https://github.com/SovereignCloudStack/issues/issues/233
- [x] https://github.com/SovereignCloudStack/issues/issues/261
- [x] https://github.com/SovereignCloudStack/issues/issues/293#issuecomment-1557396841
- [ ] As DevOps Team (SCS Customer) I'm able to use terraform (example for Infra-as-Code tooling) across SCS clouds (i.e. with a federated account provided in some external IAM (AzureAD/ADFS/freeIPA/whatever)
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by reqa** [comment]
FYI: Patch submitted upstream for review https://review.opendev.org/c/openstack/keystoneauth/+/869876

**Comment by fkr** [comment]
Discussed the errors (https://zuul.opendev.org/t/openstack/build/c35dad8e0d624af8943ed13a4aa68b90) with @osfrickler and the error likely is unrelated to the patch set. 
Recommendation is to join the irc keystonemeeting next week.

**Comment by fkr** [comment]
Patch has been merged upstream and will be part of Antelope.
We have to discuss wether or not we want to have it backported to Zed.
This depends on wether or not Antelope is the release we're going to jump to as part of R5.

**Comment by garloff** [comment]
This one is complete. Testing in #447.
