### ISSUE TITLE
Write out personas

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#192]
As a SCS Product Owner a good understanding of the various personas are needed.
As a SCS development community we need the personas to have a common understanding when talking about the various roles.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] There exists a set of documents that describe the various personas in the SCS ecosystem
- [ ] The personas are understood by everyone and serve as a way of common understanding
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
