### ISSUE TITLE
Refine Testbed Defaults and Documentation for easier getting started

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#193]
As a SCS Developer as well as a SCS Operator who is a first time to the SCS environment the testbed is my first technical contact. This should really get me started.

## Definition of Ready:

- [ ] Epic is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] [Make "Getting started" for new uses as simple as possible](https://github.com/osism/testbed/issues/1366)
- [ ] [Document use-cases of the testbed](https://github.com/osism/testbed/issues/1367)
- [ ] [Add a prep target to the Makefile](https://github.com/osism/testbed/issues/1368)
- [ ] [Adjust defaults for testbed](https://github.com/osism/testbed/issues/1369)
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
