### ISSUE TITLE
Different ceph cluster for separate az

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#217]
WIP - needs refinement 

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] https://github.com/osism/issues/issues/343
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by linwalth** [comment]
since i am invested in this topic i can kindly offer my assistance in working out this feature :)

**Comment by fkr** [comment]
Should be refined until second week of january.
@fkr to do a refinement with @ppkuschy and @ra-beer
