### ISSUE TITLE
OpenStack Flavor Manager for SCS Operators

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#236]
As a SCS Operator I need a reliable way of managing flavors on my Open Stack cloud.
As SCS we need to prepare tools to check against the standards. These tools may be used
by SCS operators to validate their setup.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] https://github.com/SovereignCloudStack/issues/issues/235
- [x] https://github.com/osism/openstack-flavor-manager/issues/1
- [x] https://github.com/SovereignCloudStack/issues/issues/296
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/Docs/pull/163

**Comment by tibeer** [comment]
@fkr even though this topic is in heavy discussion, a first "stable" version of the flavor manager is now available: https://github.com/osism/openstack-flavor-manager/pull/9. What would be a good place/good places to document this?

**Comment by fkr** [comment]
Discussion in Team IaaS call: this could be part of a 'Howto that covers the user journey of becoming a SCS compliant CSP".
Furthermore @garloff suggested to link this tool in the flavor standard.

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v2-flavor-naming.md should carry a section on this.

**Comment by tibeer** [comment]
@fkr this has been completed and can be closed.
