### ISSUE TITLE
MVP1: Status Page Application for SCS Operators

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#239]
## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] https://github.com/SovereignCloudStack/issues/issues/238
- [x] https://github.com/SovereignCloudStack/issues/issues/240
- [x] https://github.com/SovereignCloudStack/issues/issues/262
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
