### ISSUE TITLE
Metric collection in the iaas reference implementation

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#269]
As a CSP I want have reliable metric collection as a foundation for solid billing.

## Definition of Ready:

- [ ] Outcome of the epic is clear and understood by the whole team

## Definition of Done:

- [ ] ADR that lays out the design decisions exists
- [ ] It has been evaluated that the chosen approach suffices for our purposes
- [ ] gnocchi and ceilometer are available in deployed testbeds
- [ ] Playbooks exists to create usage
- [ ] Define and document the required datasets that need to end up in gnocchi
- [ ] Assure that the datasets stored suffice
- [ ] There is a documented consent and documented definition which openstack objects are relevant for metrics collection
- [ ] There exists a documented way of adding / removing components from metrics collection
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
@fkr and @cah-link will do a refinemet of this epic in this week in order to assure it reflects the current state of wisdom.

**Comment by fkr** [comment]
Further work for the Jena sprint in regard to this will be discussed on Monday 28th
