### ISSUE TITLE
OSISM: Roles / Parameter documentation

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#27]
As a SCS Operator and/or SCS Integrator I expect to have all parameters that are covered by the ansible collections that are being used to be documented.

For the documentation the [zuul sphinx extension](https://opendev.org/zuul/zuul-sphinx) should be used to properly generate the documentation from within the roles.

Example with zuul sphinx extension:

https://opendev.org/zuul/zuul-jobs/raw/branch/master/roles/add-fileserver/README.rst

https://zuul-ci.org/docs/zuul-jobs/log-roles.html#role-add-fileserver

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:
- [x] Parameters of [mapping1](https://github.com/osism/mappings/blob/main/mapping1.yml) documented
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

### Issues

- [x] #61 
- [x] #35 
- [x] #36
- [x] https://github.com/osism/issues/issues/235

**Comment by fkr** [comment]
Evaluation of Zuul Sphinx Extension has shown, it is too much centered around Zuul.
https://github.com/osism/issues/issues/185.
Needs to be forked to be of use.

#61

**Comment by garloff** [comment]
20 PRs from Ramona in progress. (Jens & CB & MF reviewing & fine-tuning).
Cleaning up along the way, avoiding redundancy.
