### ISSUE TITLE
Validations for deployment Environments

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#28]
In order to assure that a deployment is functional and properly rolled out validations need to be run.
Furthermore in order to have good coverage in CI, validations are necessary.

## Definition of Ready:

- [ ] #27 
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
Refactoring will be done until Friday EOB.
