### ISSUE TITLE
Use SCS in air-gapped environments

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/issues#280]
As an operator, I want to be able to to deploy SCS environments without access to public internet resources.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team
- [x] https://github.com/osism/testbed/pull/1496
- [x] https://github.com/osism/ansible-collection-services/pull/960

## Definition of Done:

- [x] https://github.com/osism/issues/issues/331
- [x] https://github.com/osism/issues/issues/408
- [x] https://github.com/osism/testbed/issues/1439

## Additional resources

Split story originated from #90 

![217482790-e2e058bb-a674-48a7-ae32-0f47d1852aa4](https://user-images.githubusercontent.com/39375770/219372364-9311e50d-4dcc-4814-9b50-90da3ee011c1.png)
