### ISSUE TITLE
MVP2 for status-page application

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#285]
In order to move from our MVP0 and MVP1 to a first ready-to-be used variant of our status page we will do a third MVP. 
The goal of this MVP is to have a status page up and running for the SCS infrastructure.

## Definition of Done:

- [x] https://github.com/SovereignCloudStack/issues/issues/281
- [x] https://github.com/SovereignCloudStack/issues/issues/282
- [x] https://github.com/SovereignCloudStack/issues/issues/283
- [x] https://github.com/SovereignCloudStack/issues/issues/284
- [x] https://github.com/SovereignCloudStack/issues/issues/222
- [x] #365 
- [x] #366
- [x] ~#367~
- [x] #377
- [x] https://github.com/SovereignCloudStack/issues/issues/286 (this involves a basic deployment "howto")
- [x] https://github.com/SovereignCloudStack/issues/issues/241
- [x] #178
- [x] https://github.com/SovereignCloudStack/standards/pull/286
- [x] https://github.com/SovereignCloudStack/standards/pull/296
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
