### ISSUE TITLE
Filesystem-as-a-Service

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#289]
As a SCS Operator I want to have the possiblity to offer Filesystem-as-a-Service in order to accomodate
needs such as RWX on the KaaS layer but also to offer shared storage between VM instances to customers.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
