### ISSUE TITLE
Revise existing osism documentation

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#29]
As a SCS operator as well as a SCS integrator, I rely on precise and up to date documentation. There is a [documentation](docs.osism.tech) - yet various parts have been superseeded. 

This will require splitting the documentation, as the current documentation is a monolith that contains:

- deployment
- scaling
- operating
- ...

For this the documentation needs to be restructured and partitioned into proper chapters.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

### Issues

- [x] #37 
- [x] #62

**Comment by garloff** [comment]
Issues are done, do final review with Felix to close the epic.
