### ISSUE TITLE
Observability for the KaaS for the Operator

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#291]
As a SCS Operator I need to have a clear understanding of the health of managed clusters on the KaaS layer.

WIP - needs refinement

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by matofeder** [comment]
@fkr, @o-otte view the suggested issues for the upcoming phase of MVP (MVP1):

- [ ] https://github.com/SovereignCloudStack/issues/issues/449
- [ ] https://github.com/SovereignCloudStack/issues/issues/450
- [ ] https://github.com/SovereignCloudStack/issues/issues/451
- [ ] https://github.com/SovereignCloudStack/issues/issues/452
- [ ] https://github.com/SovereignCloudStack/issues/issues/495
- [ ] https://github.com/SovereignCloudStack/issues/issues/524
- [ ] https://github.com/SovereignCloudStack/k8s-observability/issues/32

**Comment by matofeder** [comment]
@fkr 
At today's SIG monitoring meeting, we discussed the DoD list proposal for MVP-0, https://input.scs.community/monitoring-mvp-0#. 
As @o-otte agreed with it, I would like to ask you whether I can edit the epic description according to the proposed DoD. Afterward, I will create issues from the DoD open items, and then the Gonicus team could easily contribute to MVP-0.

**Comment by fkr** [comment]
yes - i think, that makes a lot of sense!

**Comment by matofeder** [comment]
See the high-level architectural diagram, which illustrates the concept of MVP-0

![monitoring_hybrid_mvp0](https://github.com/SovereignCloudStack/issues/assets/17620218/26fbcf55-3a6b-4498-a6f1-1b70049da9a8)

EDIT(27/11/2023): An update that incorporated insights from SCS Sig Monitoring/SCS team OPS meeting

**Comment by matofeder** [comment]
All DoDs for MVP0 and beyond have been fulfilled as the last missing piece has been merged https://github.com/osism/testbed/pull/1855
