### ISSUE TITLE
Disk Encryption at Operator level

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#30]
As operator I want to make sure that data stored on disks / SSDs is always encrypted. I need the nodes to get their keys reliably.

This helps with BSI C5.
This protects against disks not decomissioned securely.

Solution: tang servers distribute keys to all nodes.
HA: tang deployed on manager and all controllers.
Key cycling: Create new metadata in LUKS and update keys on all tangs.

Solutions needs to be as decentralized as possible in order to minimize SPOF.

Scenarios:

- I want to protect against loss of single disks in case of defects
- I want to protect against loss of complete server (example: edge nodes or moving the contents of a datacenter)

## Definition of Ready:

- [x] User Stories are properly written out.
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #69 
- [x] #70
- [ ] #71
- [x] #102
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by matfechner** [comment]
https://github.com/osism/documentation/pull/401

**Comment by matfechner** [comment]
Release Notes https://github.com/osism/release/blob/main/notes/4.0.0/NOTES.md

"LUKS encryption is now documented and enabled in the testbed by default"

**Comment by matfechner** [comment]
Design Document update https://github.com/SovereignCloudStack/Docs/pull/85

**Comment by berendt** [comment]
Move to blocked. the necessary testbed with the Intel system in it is being installed at the moment.
