### ISSUE TITLE
Cluster Stack Operator

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#326]
As an SCS provider, I want to have operators to create and maintain my clusters based on SCS Cluster Stacks in an automated manner. I also want to be able to modify this operators for my specific cases.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #327
- [x] #328
- [ ] #331

**Comment by fkr** [comment]
Currently in POC state, this is not reflected in the stories so far. Likely good to further refine the epic in order to have fine-grained artefacts to work on.

**Comment by jschoone** [comment]
First design document in discussion, see https://github.com/SovereignCloudStack/docs/pull/50

**Comment by jschoone** [comment]
@SovereignCloudStack/syself since we currently discuss this and this should be part of Release 5, please make sure this stories are still correct.
Otherwise please adjust them or create new ones to track your work.
