### ISSUE TITLE
Generic Operator to apply Cluster Addons

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#327]
As an SCS user/provider I want to have an operator to maintain my clusters by just providing cluster stack definitions.
The operator should be able to apply all CAPI objects fro the cluster stack, fetch new releases, delete old objects. It should also handle the life cycle of the cluster add-ons and make sure that defined Helm charts are applied in the workload cluster.

## Tasks

- [ ] Define API that contains generic objects and define how they interact with each other and provider-specific objects
- [ ] Implement life cycle of CAPI objects that have to be downloaded from the release and applied in the cluster
- [ ] Implement capability to fetch automatically for new releases of a certain cluster template
- [ ] Implement capability to delete old and unused CAPI objects automatically

**Comment by jschoone** [comment]
This is done by https://github.com/SovereignCloudStack/cluster-stack-operator/
