### ISSUE TITLE
Mirror deb packages with aptly

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/issues#330]
# Vision

We want to enable the SCS consumers to hold mirrors of deb packages. This will allow them to reduce their dependency from upstream mirrors and will also enable them to have slightly faster deployments of new SCS IaaS nodes. In a larger scope, this is also a preparation for the air-gapped possibility of SCS. The goal is to provide a capability to initially setup the mirror with all required packages and then update them on a periodic basis. The period itself is flexible.

## Definition of Ready:

- [x] User Story is small enough to be finished within one release cycle
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [x] #334
- [x] #335
- [x] #336
- [x] #337
- [x] #338

## Acceptance criteria

- [x] Aptly is containerized
- [x] Wrapper script is capable of nearly all necessary maintenance steps
- [x] Software can be deployed on kubernetes
- [x] Periodic updates are working

**Comment by fkr** [comment]
Marked as 'needs refinement'. @tibeer and me are discussing how this can be structured into an epic with well structured stories.
@tibeer thanks for this good input already!

**Comment by tibeer** [comment]
Completed.
