### ISSUE TITLE
Customer facing disk encryption

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#34]
As a user, I want to have the option to run my nodes with disk encryption with a key that I own.

## Definition of Ready:

- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

### Issues

- [x] #31 
- [x] #32 
- [x] #33
