### ISSUE TITLE
MVP for Central SCS Api

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#364]
We want to build a MVP for a Central SCS Api.

## Definition of Done:

- [x] The architecture as well as the reasoning (aka: scope) of the MVP is clearly understood by the team
  - Single K8s Cluster for now, with tenancy via namespaces
- [x] I (as a CSP) want to be able to onboard a customer to the central API (ideally but not necessarily using kubectl) - #372 
- [x]  I (as a CSP customer) want to get a kubeconfig in order to access the central API (securely) - #373 
using exec auth plugin that does OAuth2 Device Auth Flow
- [x] I (as a CSP customer) want to kubectl apply VMs in OpenStack - #374 
- [x] I (as a CSP customer) want to kubectl apply a Kubernetes Cluster ~~and get back a working kubeconfig (that enables me to talk to the created cluster)~~ - #375 
- [x] I (as a CSP customer) want to kubectl apply an IdP identity federation to my (customer owned) IAM - #376

**Comment by joshmue** [comment]
Also see #486 where progress partially regarding deployment automation, installation concept/documentation is tracked.
