### ISSUE TITLE
Analyse IAM design for security weaknesses

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#388]
As an SCS operator, I want to be sure that the Identity and Access Managment (IAM) design does not contain flaws that would allow users to escalate privileges, impersonate others or otherwise get access to information not intended for them.

- [ ] #358 keystone multivalue

 _______, I want ______ so that ____.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
