### ISSUE TITLE
Confidential Computing - Secure all the enclaves

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#39]
# Customer view

As a SCS Customer, I want to place workloads onto a SCS environment where I can be sure that the operator can't view the contents of memory enclaves in order to enable me to run data sensitive applications.

Example use-cases are:

- credential handling (eg. Vault or similar)
- health care data where ____ is a checkbox requirement

# Operator view

As a SCS operator, I want to have an offering to target customers from certain segments (eg. healthcare) that have compliance requirements 

As a SCS operator, I want to make use of a technology where I can delegate the trust issue to.

As a SCS operator, I have a high interest to make sure the platform I offer fullfills typical requirements for tender processes.

## Value proposition of confidential computing over tenant separation

/// FIXME

## Definition of Done:

- [ ] #40 
- [x] #41 
- [ ] #42
- [ ] #43
- [ ] #44
- [x] #45
- [ ] #245
- [ ] #246 
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
We are trying to figure out what https://github.com/intel/secured-cloud-management-stack is all about. I think we will be able to coordinate with the other Intel BU next week.

**Comment by berendt** [comment]
AI: Describe the steps (migrating patchset to master branch, test on Devstack, integration in Kolla images) in detail

**Comment by fkr** [comment]
Basically the interest in this topic (on the IaaS level) was very low, especially for the SGX case.
