### ISSUE TITLE
MVP0: Cluster Stack Operator

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#401]
As an SCS user, I want to have cluster classes in my management cluster from specific cluster stack versions so that I can create clusters based on it.

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Defining Custom resources and API
- [ ] Structuring repo and Makefile (DevOps)
- [ ] Cluster stack controller creating cluster stack releases
- [ ] Cluster stack release controller applying objects
- [ ] ADR: High-level cluster stack object creating sub-objects
- [ ] ADR: Talking to Kubernetes API in Go (PR is out)
