### ISSUE TITLE
Create Cluster Stack for Openstack

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#425]
As an SCS developer, I want to have Openstack support implemented as Cluster Stack so I can deploy Kubernetes on Openstack using the Cluster Stack approach.

### User Stories
- [ ] Create Helm Chart for Cluster Addons (can be tested with helm apply)
- [ ] #498
- [ ] Create node images and add them so that they can be used by the CSO  
- [x] #492
- [x] #493
- [ ] Test everything with Tilt in the OpenStack Provider Repo and make sure workload clusters are created as expected
