### ISSUE TITLE
Enhancements of the SCS Zuul Deployment to increase reliability

### ISSUE THREAD

**Issue by o-otte** [SovereignCloudStack/issues#428]
The SCS Zuul is currently up and running, but recent incidents showed there are opportunities to improve the reliability. 

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [x] #429
- [ ] #430
- [x] #432
- [ ] #433
- [x] #398
- [ ] #664
- [ ] Documentation has been updated

**Comment by okautz** [comment]
Done with new Instance at https://zuul.sovereignit.cloud
