### ISSUE TITLE
Create Cluster Stack Provider Openstack

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#496]
As an SCS Developer, I want to implement Openstack as Cluster Stack Provider so that I can manage my Kubernetes clusters on Openstack using the Cluster Stack approach.

## Definition of Ready:

- [x] Cluster Stack Provider Openstack repo exists
- [x] Cluster Stack Provider "Boilerplate" is present in repo

## User Stories

- [x] #506
- [ ] Test it with Tilt and OpenStack Cluster Stacks if workload clusters look as expected

**Comment by batistein** [comment]
The repo is now available here: https://github.com/SovereignCloudStack/cluster-stack-provider-openstack
@jschoone the user stories indicate that this issue is not finished. But in general the first step is now done. I would suggest to create new issues for the tasks which are below the User Stories
