### ISSUE TITLE
Migrate features from k8s-cluster-api-provider

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#502]
As an SCS developer, I want to migrate the features from the [k8s-cluster-api-provider](https://github.com/SovereignCloudStack/k8s-cluster-api-provider) so that I have the same feature set available in Cluster Stacks.

## User Stories

- [ ] Identify features which needs to be migrated
- [ ] Identify which features needs to be implemented in CAPO/OCCM
- [ ] Find an alternative deployment method for the shell scripts
