### ISSUE TITLE
OpenStack Health Monitor as a way to blackbox monitor via API

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#53]
As a SCS Operator I want to have a blackbox monitoring of my SCS stack.
As the SCS Project we want to be able to monitor the health of SCS
installations.

Blackbox monitoring in this scope is defined as a way to observe the
behaviour of the SCS stack from the outside by interacting with the API
doing CRUD operations on the various objects.
As a SCS Operator I need to be informed (“alerted”) if the outcome of an
operation does not match the expected result.
The blackbox monitoring is defined as done if it can replace the current
openstack health monitor.

## Definition of Ready:

- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
