### ISSUE TITLE
New deployment method in OSISM - greenfield

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#534]
### Definition of Ready:

- [ ] New rook deployments are possible via OSISM
- [ ] Rook deployments are manageable and customizable after and during deployment (TODO: different story?)

### Definition of Done:

- [ ] All acceptance criteria are met (TODO: shall we define thoose?)
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

### Tasks

- [ ] Analyze old deployment method in OSISM
    - [ ] Which ceph ressources are deployed by OSISM?
    - [ ] How is the OpenStack integration done?
    - [ ] Are there any special characteristics how ceph is deployed in OSISM?
- [ ] Design a new deployment process
    - [ ] Which rook CRDs have to be deployed?
    - [ ] How do we deploy the rook cluster? Plain yaml vs. Helm
    - [ ] Do we have to reproduce special characteristics of the old method?
- [ ] Implement the new deployment process
- [ ] Test the new deployment process
- [ ] Document the new deployment process

**Comment by fkr** [comment]
Prepped by @brueggemann - thanks!

**Comment by NotTheEvilOne** [comment]
Note: Further analysis showed that LVM creation for (encrypted) Ceph OSDs currently provided by [OSISM](https://github.com/osism/ansible-playbooks) can be optimized to be generated on the fly by Rook utilizing appropriate [OSD configuration settings](https://github.com/rook/rook/blob/381556a1b41f6e8b037d9b43dd8e4d7472b052cd/Documentation/CRDs/Cluster/ceph-cluster-crd.md?plain=1#L334). Resulting LVM will have the same set-up as current manual

**Comment by berendt** [comment]
> Note: Further analysis showed that LVM creation for (encrypted) Ceph OSDs currently provided by [OSISM](https://github.com/osism/ansible-playbooks) can be optimized to be generated on the fly by Rook utilizing appropriate [OSD configuration settings](https://github.com/rook/rook/blob/381556a1b41f6e8b037d9b43dd8e4d7472b052cd/Documentation/CRDs/Cluster/ceph-cluster-crd.md?plain=1#L334). Resulting LVM will have the same set-up as current manual

We have explicitly not done this on-the-fly (which is also possible in ceph-ansible). It would be good if the existing approach with prior creation of LVs and subsequent processing by Rook is also possible (is fine as optional, it does not have to be the default). There are various deployments where this is explicitly required and is not wanted on-the-fly.

**Comment by NotTheEvilOne** [comment]
Thanks for your fast input @berendt, we will have a further look how existing LVM devices can be supported not only for migration but also new setups as well if requested.

**Comment by yeoldegrove** [comment]
@berendt At the moment it looks like existing LVM devices (and dmcrypt on top) is not supported by rook. 
This is somewhat stated in https://rook.io/docs/rook/latest-release/CRDs/Cluster/ceph-cluster-crd/#osd-configuration-settings
```
lvm --> "metadataDevice must be "", osdsPerDevice must be 1, and encryptedDevice must be false"
```

If we try to roll out fresh OSDs on rook with pre-existing LVM (not yet dmcrypted), we land in this code path: https://github.com/rook/rook/pull/10855/files#diff-70d9ded8ec1e299893633b3bfaf85bfe3f02704c3b477b5e5453b86be6b51338R495

```
│ provision 2024-04-30 09:19:36.891589 I | cephosd: "/dev/ceph-007df0bf-7881-5cbf-aad5-868d1c480f67/osd-block-007df0bf-7881-5cbf-aad5-868d1c480f67" found in the desired devices (matched by link: "/dev/ceph-007df0bf-7881-5cbf-aad5-8 │
│ provision 2024-04-30 09:19:36.891594 I | cephosd: logical volume "dm-1" is not picked because encrypted OSD on LV is not allowed    
```

As stated by @NotTheEvilOne ... the encrypted LVM volumes created by rook look exactly the same than the currently created onces (via `osism apply ceph-create-lvm-devices`):

```
dragon@testbed-manager:~$ ssh testbed-node-0 sudo ls -1 /dev/ceph*/*
/dev/ceph-05c12b07-fbdd-48bd-aac6-3a0114bbd659/osd-block-8c4c4f43-3e12-4576-b8d3-5cca20d50d9c
/dev/ceph-e1d4efad-0e55-4456-adb9-645717be1320/osd-block-827bd11a-4c2e-4fea-bbbc-bb01b856a467
```

**Comment by berendt** [comment]
Then that's how it is. I wouldn't want to expand Rook because of that. We have to document that this is the case.
