### ISSUE TITLE
Migration to new deployment method - rookify

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#535]
As a user, I want to be able to migrate my old ceph setup to Rook so that the migration process is as smooth as possible.

### Definition of Ready:

- [ ] Migrations are possible
- [ ] Conditions if a migration is possible are documented
- [ ] Possible pre-migration tasks are documented

### Definition of Done:

- [ ] All acceptance criteria are met (TODO: shall we define thoose?)
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

### Tasks

- [ ] Implement tools for the migration to rook
    - [ ] Framework implementation
        - [x] Modular approach
        - [ ] Unit tests for framework
    - [ ] Migration modules for ceph daemons
        - [ ] MONs
        - [ ] MGRs
        - [ ] OSDs
        - [ ] RGWs
        - [ ] MDSs
    - [ ] Migration modules for ceph resources to rook CRDs
        - [ ] CephBlockPool
        - [ ] CephFileSystem
        - [ ] CephObjectStore
     - [ ] Unit tests for migration modules
- [ ] Test the new migration tools
    - [ ] Testbed migration
    - [ ] Test with cloud provider setups
- [ ] Document migration path and tools
    - [ ] conditions
    - [ ] pre-migration tasks
    - [ ] configuration files

**Comment by fkr** [comment]
Prepped by @brueggemann - thanks!

**Comment by fkr** [comment]
this issue is outdated and I see no benefit of keeping it around. Please re-open if necessary.
