### ISSUE TITLE
KaaS Hackathon Task List

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/issues#539]
# Regarding R6

- [x] SovereignCloudStack/cluster-stacks#37
- [x] SovereignCloudStack/cluster-stacks#38
- [x] SovereignCloudStack/cluster-stacks#39
- [x] SovereignCloudStack/issues#544
- [x] https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/711
- [x] https://github.com/SovereignCloudStack/issues/issues/541
- [x] Revive the idea of a shared cluster
- [x] SovereignCloudStack/issues#553
- [x] #567
- [x] https://github.com/SovereignCloudStack/cluster-stacks/issues/26
- [x] https://github.com/SovereignCloudStack/cluster-stacks/issues/28

# if time permits

- [ ] <https://github.com/SovereignCloudStack/issues/issues/540>

# Regarding R7
- [ ] Design a UI for Central API
- [ ] Cover other Providers
