### ISSUE TITLE
parametrizing test scenarios

### ISSUE THREAD

**Issue by piobig2871** [SovereignCloudStack/issues#554]
Create parametrization for the creation and deleting of network in tests

## Definition of Ready:

- [ ] Tests are ruined with specific parameters

## Definition of Done:

- [ ] Solution is tested
- [ ] Codes are provided to the repository

**Comment by Erik-Kostelansky-dNation** [comment]
Solved in following [PR](https://github.com/SovereignCloudStack/scs-health-monitor/pull/10)
