### ISSUE TITLE
POC for OVN Exporter in Testbed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#67]
In order to support the merge upstream of the OVN exporter, we need to get a POC on a single-node setup up and running.

## Definition of Ready:

- [ ] #21 
- [x] #63 
- [ ] #64 
- [ ] #65 
- [ ] #66 
- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] A testbed installation features a POC for HA monitoring of OVN
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated
