### ISSUE TITLE
Overview over Cluster Settings

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#74]
As a SCS KaaS developer, I want to have an overview over the settings that various cluster management solutions offer.
https://scs.sovereignit.de/nextcloud/apps/files/?dir=/Sovereign%20Cloud%20Stack/Technology&fileid=5021

- [ ] SCS: #75 - Kurt, Sven, Eduard
- [x] Gridscale: #76 - Andrej & Ibrahim
- [x] Hetzner: #77 - Janis & Sven
- [ ] Cloud&Heat: TBD (-> Jonas)
- [ ] Tanzu: TBD (-> Toens)
- [ ] Gardener: #81 - Malte
- [ ] GiantSwarm: TBD (Kurt -> Cornelius Keller / )
- [ ] Rancher: TBD (? Andrej - possibly outdated / B1)
- [ ] Kubermatic: TBD (? B1?)

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by garloff** [comment]
Discussion 2022-05-23:
* Avoid having too high entry-barriers  and complexity just to have a base SCS compatibility
* Focus on core!
* Things that can easily be added by the customer afterwards should not be part of the base requirement.
* Example: ingress: Requires load-balancer, which should be required. (Ingress should not be required.)

**Comment by garloff** [comment]
Node images discussion:
- Upstream CAPI images exist (but are not meant for production)
- Provider-independent images are very hard to do (hard to avoid provider-specific things)
- So we would to define requirements to images rather than the images themselves
- Still be useful to feed standard requirements upstream

Need discussion with upstream CAPI image folks.

**Comment by garloff** [comment]
Discussion on node-problem-detector:
- Can be deployed as daemonset, so does not need to be integrated in node image
- daemonset is under user control, so this should be preferred (over the systemd unit approach)
- Requirement for node images would be that they don't break the daemonset way of deploying n-p-d

**Comment by fkr** [comment]
This issue is marked for R3. Will this be scope of R4?
