### ISSUE TITLE
Migration from docker to podman in kolla-ansible

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#87]
As the SCS project we have a high interest in having a healthy OSS upstream ecosystem. The future direction of docker is unclear, with podman exists a healthy OSS replacemeny governed by the community. We should see about moving upstream kolla-ansible towards podman. 
Upstream is open to this and it has been discussed during the last PTG.

See: 

- [x] https://github.com/osism/issues/issues/223

## Definition of Ready:

- [ ] User Stories are all layed out
- [ ] We have a clear understanding of timeline and work that needs to be done
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by berendt** [comment]
Docker is very healthy at the moment. IMO there is no need to force a migration to podman at the moment.
