### ISSUE TITLE
Mirroring Infrastructure

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/issues#90]
As an operator, I want to be able to build artifacts and deploy and maintain SCS environments without access to public internet resources. Therefore software needs to be created allowing mirroring deb, pypi, container and ansible role/collection assets. Initially these assets need to be mirrored to internal mirrors delivering to our CI-CD systems.

## Definition of Ready:

- [x] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- ~[ ] https://github.com/osism/issues/issues/88~
- [x] https://github.com/osism/issues/issues/186
- ~[ ] https://github.com/osism/issues/issues/187~
- [x] https://github.com/osism/issues/issues/330
- [x] https://github.com/osism/issues/issues/348
- [x] https://github.com/osism/public-services/issues/28
- [x] Create ansible-galaxy mirror software: https://github.com/osism/python-ansible-wormhole
- [x] Create bandersnatch api frontend software: https://github.com/osism/python-banderctl
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Blogpost on Air-Gapped has been published
- [x] Release Notes have been updated

**Comment by garloff** [comment]
Package mirrors (distro repos, language package mirrors), image mirrors, git(hub) mirrors, etc.

**Comment by berendt** [comment]
Tim has started with it. but is now on vacation for the time being.

**Comment by berendt** [comment]
This is nearly finished. I will check the pending reviews the next days. Maybe this can be merge just before R3.

**Comment by fkr** [comment]
next step: re-evaluate pulp

**Comment by garloff** [comment]
January

**Comment by fkr** [comment]
It is planned to finalize this epic for R4, so that R4 ships with air gapped install support.

**Comment by tibeer** [comment]
@tibeer provide an overview of the status (open points, done stuff, etc.)

**Comment by tibeer** [comment]
Intermediate architecture view:
![airgap](https://user-images.githubusercontent.com/39375770/217482790-e2e058bb-a674-48a7-ae32-0f47d1852aa4.png)

**Comment by tibeer** [comment]
ToDo's:
- Deploy infrastructure mirros
- Modify testbed to use squid: squid points to infrastructure mirrors
- Extend testbed with own mirror services (real airgap)

**Comment by fkr** [comment]
Split this epic into two:

1) Mirroring Infrastructure 
2) Transparent usage of proxy and mirroring infrastructure

**Comment by fkr** [comment]
Discussed in todays IaaS call: Blogpost will be updated to reflect the changed requirements and then is ready to go.

**Comment by fkr** [comment]
Blogpost has been updated by @tibeer. @fkr to review and merge today.
