### ISSUE TITLE
Testbed setup with multiple Keycloaks or at least multiple realms within one keycloak

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#95]
As a SCS developer, we want to test federation. To do that we need a test setup that either features multiple Keycloaks or at least multiple realms within a keycloak.

## Definition of Done:

- [x] #96 
- [x] #195 
- [x] #196
- [ ] https://github.com/osism/testbed/issues/1402  (see also https://github.com/osism/testbed/pull/1404)
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by garloff** [comment]
Two testbeds with one keycloak each are available. (Legacy keycloak in testbed.)
Both exposed to each other, but don't accept each other's certs.
New, quarkus-based keycloak might complicate things.

## TODO:
- [ ] import CA from other host
- [ ] avoid regenerating a (self-signed) cert on container restart
- [ ] May revert to official (let's encrypt?) certs to avoid manual signing and importing

**Comment by fkr** [comment]
@matfechner and @fkr will formulate the proper user stories to actually have a proper DoD in this epic.

**Comment by fkr** [comment]
maybe this issue is obsolete, because the expired self-signed certs have been replaced and now all should be peachy.
Please verify.

**Comment by fkr** [comment]
For now we put this on hold until further notice, since it is not clear wether we will proceed with keycloak.
